name: subgraphx
channels:
  - nvidia
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - pip>=21.2
  - python>=3.8
  - jupyterlab
  - cudatoolkit=11.3
  - pytorch>=1.10
  - pytorch-cluster
  - pytdc
  - pyg
  - pip:
    - -r requirements.txt
